name: Deploy to Gitee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^7.4.0

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build

      - run: |
          cd .vitepress/dist
          git init
          git config user.email "yyx990803@gmail.com"
          git config user.name "Evan You"
          git add .
          git commit -m "update docs"
          git remote add github https://vue-bot:${{ secrets.VUE_BOT_TOKEN }}@github.com/vuejs/cn.vuejs.org-deploy.git
          git push github HEAD:gh-pages --force
          git remote add origin https://yyx990803:${{ secrets.GITEE_TOKEN }}@gitee.com/vuejs-cn/vue3-docs-cn.git
          git push origin HEAD:master --force
